version: 2

jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/base:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - grow-cache-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Grow Intall
          command: grow install

      - save_cache:
          key: grow-cache-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Test Build
          command: grow build

workflows:
  version: 2

  build:
    jobs:
    - build
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
              - master
    jobs:
      - build
